### ISSUE TITLE
Custom build regression in ol 3.17.x series

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/ol3#5564]
Trying to use the latest OpenLayers 3 in the official workshop context, I'm unable to build the ol-custom.js file without modifying the OpenLayers library. (PS: I've tried the build with version 3.16 using https://github.com/openlayers/workshop/pull/53 without issue, hence my title)

When running, 
 
```
node node_modules/openlayers/tasks/build.js ol-custom.json ol-custom.js
```

It failed with the following messages:

```
info ol Parsing dependencies
info ol Compiling 287 sources
ERR! compile externs/olx.js:1263: ERROR - Bad type annotation. Unknown type ol.control.ScaleLineUnits
ERR! compile  *     units: (ol.control.ScaleLineUnits|string|undefined)}}
ERR! compile                ^
ERR! compile
ERR! compile externs/olx.js:1303: ERROR - Bad type annotation. Unknown type ol.control.ScaleLineUnits
ERR! compile  * @type {ol.control.ScaleLineUnits|string|undefined}
ERR! compile           ^
ERR! compile
ERR! compile externs/olx.js:1794: ERROR - Bad type annotation. Unknown type ol.format.IGCZ
ERR! compile  * @typedef {{altitudeMode: (ol.format.IGCZ|undefined)}}
ERR! compile                              ^
ERR! compile
ERR! compile externs/olx.js:1802: ERROR - Bad type annotation. Unknown type ol.format.IGCZ
ERR! compile  * @type {ol.format.IGCZ|undefined}
ERR! compile           ^
ERR! compile
ERR! compile externs/olx.js:5899: ERROR - Bad type annotation. Unknown type ol.source.WMTSRequestEncoding
ERR! compile  *     requestEncoding: (ol.source.WMTSRequestEncoding|string|undefined),
ERR! compile                          ^
ERR! compile
ERR! compile externs/olx.js:5981: ERROR - Bad type annotation. Unknown type ol.source.WMTSRequestEncoding
ERR! compile  * @type {ol.source.WMTSRequestEncoding|string|undefined}
ERR! compile           ^
ERR! compile
ERR! compile
ERR! compile 6 error(s), 0 warning(s)
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 6
```
You will find attached a minimum project to try and confirm the issue. Instructions and corrections I applied are in it README.md file although I don't think it's the "right" way to solve the issue.

[test-ol3.zip](https://github.com/openlayers/ol3/files/346727/test-ol3.zip)

**Comment by probins** [comment]
that looks like #5475 needs reverting, though I don't atm understand why. I'll investigate

**Comment by probins** [comment]
probably related to #4945

**Comment by probins** [comment]
you can get it to compile by using the default compiler errors/warnings, i.e. remove the `jscomp_error` and `jscomp_off` sections of `ol-custom.json`. Then it will report these as warnings rather than errors. My own custom build works fine, and I'm not using IGC format either, so I don't understand why there's an error for this in one and not in the other.

**Comment by ahocevar** [comment]
Here's the problem: because these enums are symbols that are not contained in a `goog.provide`d namespace, they won't be included unless something `goog.require`s a component provided in a file that also provides the typedef. A solution would be to rename the enum symbols so they are provided by the component that uses them, e.g. `ol.control.ScaleLine.Units` instead of `ol.control.SacleLineUnits`.

**Comment by probins** [comment]
my custom build uses ScaleLine and WMTS, which are not included in this build, so for these I understand why this build fails whereas mine doesn't. But neither of these builds uses IGC/Z, so why does one produce an error and the other not?
