### ISSUE TITLE
3.13.0 gives "'undefined' is not a function (evaluating 'handler.bind(s)')"

### ISSUE THREAD

**Issue by tomchadwin** [openlayers/ol3#4706]
See: https://github.com/tomchadwin/qgis2web/issues/176

qgis2web tries to use the latest OL3 release (it works with OL3.12.1). 3.13.0, though, results in the above error (`ol-debug.js:48906`) when previewing a map in its Qt-based GUI (in a `QtWebKit.QWebView`).

What has caused this? No problem if the qgis2web-generated JS needs to be rewritten, but I don't know what the issue is, so I don't know how to fix it.

**Comment by ahocevar** [comment]
Instead of `ol.js`, use `ol-debug.js`. Then give us the exact error message and line number again.

**Comment by tomchadwin** [comment]
As detailed above:

```
'undefined' is not a function (evaluating 'handler.bind(s)')
ol-debug.js:48906
```

*Please note*: this error only occurs for me in the Qt GUI widget. In IE11 or Chrome (x64), I get no error. However, the error also disappears in the Qt GUI if I revert OL to 3.12.1, so something's not quite right somewhere.

**Comment by ahocevar** [comment]
Looks like you need a polyfill for `Function#bind()`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind.

**Comment by tomchadwin** [comment]
Great. I'll try that. Just to double-check:

1. Is the use of `Function#bind()` new to 3.13.0?

2. Is this a regression, and should the polyfill be part of OL3?

**Comment by ahocevar** [comment]
> Is the use of Function#bind() new to 3.13.0?

Yes.

> Is this a regression, and should the polyfill be part of OL3?

It is not a regression, but it should have been mentioned in the release notes. We're in the process of removing legacy code from the library. OpenLayers supports all ES5.1 capable browsers. If the target platform is something else, the application needs to provide polyfills.

We need to improve our documentation here.

**Comment by ahocevar** [comment]
See #4639.

**Comment by ahocevar** [comment]
We are using a polyfill in our examples as well. See db3ad70a3d7598254cbf11b7a6540b9fba3773ab for the change.

**Comment by tomchadwin** [comment]
Thanks for the thorough explanation and references. I'll add the polyfill tomorrow to confirm it works, and shall only reopen if it doesn't.

**Comment by tomchadwin** [comment]
Confirmation that the polyfill works. Thanks again.
