### PR TITLE
Reinsert goog.provide for enums in olx.js

### LINKED ISSUE #5564: Custom build regression in ol 3.17.x series
Trying to use the latest OpenLayers 3 in the official workshop context, I'm unable to build the ol-custom.js file without modifying the OpenLayers library. (PS: I've tried the build with version 3.16 using https://github.com/openlayers/workshop/pull/53 without issue, hence my title)

When running, 
 
```
node node_modules/openlayers/tasks/build.js ol-custom.json ol-custom.js
```

It failed with the following messages:

```
info ol Parsing dependencies
info ol Compiling 287 sources
ERR! compile externs/olx.js:1263: ERROR - Bad type annotation. Unknown type ol.control.ScaleLineUnits
ERR! compile  *     units: (ol.control.ScaleLineUnits|string|undefined)}}
ERR! compile                ^
ERR! compile
ERR! compile externs/olx.js:1303: ERROR - Bad type annotation. Unknown type ol.control.ScaleLineUnits
ERR! compile  * @type {ol.control.ScaleLineUnits|string|undefined}
ERR! compile           ^
ERR! compile
ERR! compile externs/olx.js:1794: ERROR - Bad type annotation. Unknown type ol.format.IGCZ
ERR! compile  * @typedef {{altitudeMode: (ol.format.IGCZ|undefined)}}
ERR! compile                              ^
ERR! compile
ERR! compile externs/olx.js:1802: ERROR - Bad type annotation. Unknown type ol.format.IGCZ
ERR! compile  * @type {ol.format.IGCZ|undefined}
ERR! compile           ^
ERR! compile
ERR! compile externs/olx.js:5899: ERROR - Bad type annotation. Unknown type ol.source.WMTSRequestEncoding
ERR! compile  *     requestEncoding: (ol.source.WMTSRequestEncoding|string|undefined),
ERR! compile                          ^
ERR! compile
ERR! compile externs/olx.js:5981: ERROR - Bad type annotation. Unknown type ol.source.WMTSRequestEncoding
ERR! compile  * @type {ol.source.WMTSRequestEncoding|string|undefined}
ERR! compile           ^
ERR! compile
ERR! compile
ERR! compile 6 error(s), 0 warning(s)
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 6
```
You will find attached a minimum project to try and confirm the issue. Instructions and corrections I applied are in it README.md file although I don't think it's the "right" way to solve the issue.

[test-ol3.zip](https://github.com/openlayers/ol3/files/346727/test-ol3.zip)

### PR DESCRIPTION
**Pull request by probins**
A partial revert of #5475 to fix #5564. I don't understand why this should be ok for some custom builds and not for others, but the safest is to put these `goog.provide`s back again. I tried removing `manage_closure_dependencies` but then I get other errors to do with CartoDB source - sigh.

### CODE REVIEW

**Comment by ahocevar** [comment]
See my https://github.com/openlayers/ol3/issues/5564#issuecomment-230408577 for an explanation why these problems can occur.

**Comment by ahocevar** [comment]
Thanks for the quick fix @probins.

**Comment by probins** [comment]
don't know whether it's worth cherry-picking this for a bug-fix release?

**Comment by bartvde** [comment]
yeah I'll wait a bit now to see if no new regressions show up, since this is not a critical one I guess (not many people doing custom builds I think).

**Comment by ahocevar** [comment]
I tend to agree with @bartvde that this one does not warrant a bug fix release by itself.
